---
# title: "Title"
# subtitle: "Subtitle"
# author: "Name"
# date: "`r Sys.Date()`"
# output: 
#   html_document:
#     toc: TRUE
#     toc_float:
#       collapsed: true
---

<style type="text/css">
.main-container {
  max-width: 95vw;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache = FALSE, cache.lazy = FALSE, autodep = TRUE, warning = FALSE, 
  message = FALSE, echo = TRUE, dpi = 180,
  fig.width = 8, fig.height = 5, echo = FALSE
  )
```

<!--#general comments===========================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# This is [[insert description here - what it does/solve]]
#
# By: mike gaunt, michael.gaunt@wsp.com
#
# README: [[insert brief readme here]]
#-------- [[insert brief readme here]]
#
# *please use 80 character margins
# *please go to https://pkgs.rstudio.com/flexdashboard/articles/layouts.html
# to explore the different layouts available for the flexdashboard framework
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->

<!--#library set-up=============================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#content in this section should be removed if in production - ok for dev -->
```{r}
library(tidyverse)
library(mapview)
library(tigris)
library(here)
library(sf)
```

<!--#source helpers/utilities===================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#content in this section should be removed if in production - ok for dev -->

<!--#source data================================================================
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#content in this section should be removed if in production - ok for dev 
#area to upload data with and to perform initial munging
#please add test data here so that others may use/unit test these scripts -->
```{r}


# feature = mapedit::drawFeatures() %>%
#   st_transform(4326)
# 
# roads = c("TN", "MS", "AR") %>%  
#   map(~tigris::primary_secondary_roads(state = .x, year = 2021))
# 
# roads %>%
#   reduce(bind_rows) %>%
#   st_transform(4326) %>%
#   st_filter(feature) %>%
#   saveRDS(., here("data/memphis_req/roads_tigris.rds"))
roads_1 = readRDS(here("data/memphis_req/roads_tigris.rds"))





```


<!--#SECTION NAME===============================================================
#use this header to make demarcations/section in code [delete this line]
#short description -->

<!-- # Header -->

<!-- ## Header -->

<!-- ### Header -->

<!-- #### Header -->

<!-- <details> -->
<!-- <summary>Click to Expand</summary> -->

<!-- Example of expandable box.  -->

```{r}
mapview(roads_1, zcol = "FULLNAME", legend = F)
```




<!--end-->






